add files
KatarzynaKopowska/Exercises pull request #1
Opened 2019-11-21 19:50 UTC by KatarzynaKopowska

2019-12-03 02:04 UTC, Backscratcher requested changes
Looknij :D

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/requirements.txt
> +python==3.7.0
Czy to jest prawidłowa instrukcja na windowsie ? Bo mi coś się wydaje, że nie. Generalnie jak chcesz pokazać jaka to jest wersja pythona, to piszesz to w README.md np. :)

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/config.py
> +no_fluff = "https://nofluffjobs.com/api/search/posting?fbclid=IwAR3JHIQyCTzFkaAjlFPpVqVnAYJ5W9KtDLNhmFsE--18mknYJFKE5XzSpVs"
O ile szanuje używanie przez Ciebie config'a to wydaje mi się to tutaj lekko nietrafione ze względu na design całego zadania.

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +import requests
Przerobiłbym to trochę, proszę zobacz to co stworzyłem poniżej. Nie jest to rozwiązanie idealne ale trochę inaczej pokazuje podejście obiektowe i pojęcia abstrakcji używania interfejsów oraz trochę takiego magicznego podejścia python'owego - co tak naprawdę było celem tego zadania (następnym razem postaram się trochę lepiej opisywać zadania, które Ci daje :) ). Jak masz pytania, możemy je też omówić (np. prywatnie)

```
import collections

import requests


JobOffer = collections.namedtuple(
    "JobOffer", ("position", "company", "url", "salary", "source"),
)


class BaseScraper:
    """Basic abstraction for services to handle serializing data from service
    and wrap them around data class.`
    """
    url = None
    data_class = None

    def get_offers(self):
        """Get a container of API data from self.url."""
        raise NotImplementedError

    def parse_offer(self, data):
        """Parse single API data structure into self.data_class."""
        raise NotImplementedError


class NoFluffJobsScraper(BaseScraper):
    url = "https://nofluffjobs.com/api/search/posting"
    data_class = JobOffer

    def get_offers(self):
        return requests.get(self.url).json()["postings"]

    def parse_offer(self, data):
        data = {
            "position": data.get("title"),
            "company": data.get("name"),
            "url": data.get("url"),
            "source": "nofluffjobs",
            "salary": "-",
        }
        return self.data_class(**data)


class JustJoinITScraper(BaseScraper):
    url = "https://justjoin.it/api/offers"
    data_class = JobOffer

    def get_offers(self):
        return requests.get(self.url).json()

    def parse_offer(self, data):
        data = {
            "position": data.get("title"),
            "company": data.get("company_name"),
            "salary": "{} - {}".format(
                data.get("salary_from"), data.get("salary_to")
            ),
            "url": "-",
            "source": "justjoinit",
        }
        return self.data_class(**data)


class JobScraper:
    scraper_classes = (NoFluffJobsScraper, JustJoinITScraper)

    def __init__(self):
        self.offers = []

    def scrap(self, filter_position=None):
        for scraper_class in self.scraper_classes:
            scraper = scraper_class()
            for offer_data in scraper.get_offers():
                offer = scraper.parse_offer(offer_data)
                if filter_position and filter_position in offer.position.lower():
                    self.offers.append(offer)
        return self.offers


job_scraper = JobScraper()
job_scraper.scrap(filter_position="python")
```

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +    def get_url(URL):
Fajnie, że wiesz o metodach statycznych i ta tutaj jest całkiem nieźle użyta :)

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +    def find_python_job(data, value):
`find_python_job` sugeruje znaleźienie oferty python'owej jednak w metodzie nie widać tego ponieważ nie szukamy po żadnej wartości sugerującej "python'a" tylko przyrównujemy ją do trochę mylącej zmiennej `value`.  Dlatego w swoim snippetcie dodałem po prostu zmienną `filter_position` do filtrowania po stanowisku (nie jest to super rozwiązanie ale nie piszemy tu biblioteki tylko staramy się w dosyć prosty sposób otrzymać rozwiązanie

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +        for k, v in data.items():
Starałbym się unikać takich nazw jak `k, v` tylko `key, value` jeśli podejrzewasz co w słowniku się znajdzie polecałbym używać bardziej opisowych nazw tzn.
```
słownik = {"jakies_id": [lista kolorow]}

for _id, colors_list in slownik.items()
```

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +            if type(v) == str and value in v.lower():
Do porównywania polecam bardziej używać `isinstance(obj, klass)`

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +            else:
W tym przypadku tego elsa możesz odrzucić.`pass` w takim przypadku zwraca `None` to samo osiągniesz nie robiąc tego else'a - automatycznie też zostanie zwrócony `None`.

2019-12-03 02:04 UTC, Backscratcher commented on job-scraper/main.py
> +
Spójrz na mojego snippet'a, trochę to wszystko przerobiłem i trochę inaczej operuje na zwracanych danych, mam nadzieje, że mój kod trochę Ci bardziej rozjaśni jak można pisać taki kod. Starałaś się jedną klasą i w main'ie oporządzić wszystkie dane. Ja wszystko przeniosłem do klasy i cała serializacja + przeróbka danych dzieje się w klasach i ostatnie wywołanie w main'ie sprowadza się do dwóch linijek + jakieś wyświetlenie wyniku.

2019-12-03 15:17 UTC, Backscratcher requested changes
Co do nazwy całego modułu, może zmienimy na `exercise_1` a w środku `job_scraper.py` i `main.py`

2019-12-03 15:17 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +class NoFluffJobsScraper:
Jak widzisz taki kod, jak te dwa scraper'y można z nich wyłonić wspólną abstrakcję, wspólny interfejs, klasę bazową, która służyłaby (w skrócie to co ja zrobiłem konfigurowalna zmienna klasowa `url` oraz dwie metody `get_offers` oraz `parser_offer`) jako baza dla przyszłych scraperów - tzn. jakbyśmy chcieli dodać kolejne serwisy do scrap'owania to używamy klasy BaseScraper i mamy bazę dla kolejnego scraper'a. Może nie jest to wymagane ponieważ to co tu stworzyliśmy jest dosyć proste ale pokazuje co programista miał na myśli pisząc to i ułatwia to prace innym programistom jakby chcieli się wpiąć w ten system.

2019-12-03 15:17 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +            "url": offer.get("url"),
Tu jest jeden problem, mianowicie  dany url zostanie wyprintowany jako jakiś slug `/programista-cos-tam-costam/` fajnie by było gdyby był to pełny url. Wystarczy coś takiego:
`"{}{}".format("https://nofluffjobs.com/job/", offer.get("url"))`

2019-12-03 15:17 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +                "url": "-",
Analogicznie tutaj:
`https://justjoin.it/offers/ggs-it-project-manager-krakow-srodmiescie`
`"{}{}".format("https://justjoin.it/offers/", offer.get("id"))`

2019-12-03 15:17 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +class Scraper:
Chyba zmieniłbym nazwę tego, mianowicie `ServicesScraperManager` albo `ScraperManager` coś co odróżnia od tych klas wyżej, bo może być mylące a faktycznie klasa Scraper zarządza tymi końcówkami i pozyskuje dane. Co myślisz ? :)

2019-12-03 15:17 UTC, Backscratcher commented on job-scraper/job_scraper.py
> +scraper = Scraper()
Te dwie linijki chciałbym żebyś przerzuciła do skryptu `main.py` i tam zrobiła wywołanie takie jak miałaś w poprzednim pliku `main.py` generalnie chodzi tu o pewien porządek, ponieważ jakbyś chciała zaimportować jakąś klasę z tego pliku tzn. `from job_scraper import Scraper` spowodowało by to wywołanie tych linijek i niepotrzebne ściągnięcie danych. Potraktujmy ten moduł jak "małą bilbiotekę" i nie wywołujmy tego tutaj.

Tu masz np. objaśnienie tego problemu:
https://stackoverflow.com/questions/419163/what-does-if-name-main-do

TL;DR zrób plik `main.py` w nim `if __name__ == "main" ` w którym wywołujesz np.
```
if __name__ == "__main__":
    scraper = Scraper()
    python_offers = scraper.run(filter_position="python")
    for offer in python_offers:
        print(f"{offer.position},{offer.url},{offer.salary}")
```

2019-12-04 08:38 UTC, KatarzynaKopowska commented on job-scraper/job_scraper.py
> +class Scraper:
Zgadzam się :) Done!

2019-12-06 00:09 UTC, Backscratcher requested changes
https://www.python.org/dev/peps/pep-0008/#indentation materiał do poczytania : >

2019-12-06 00:09 UTC, Backscratcher commented on exercise_1/job_scraper.py
> +        data = {"position": offer.get("title"),
Ostatnia sprawa bo jest pięknie:
```
data = {
    "position": offer.get("title"),
     "company": offer.get("company_name"),
     "salary": "{} - {}".format(offer.get("salary_from"), offer.get("salary_to")),
     "url": "{}{}".format("https://justjoin.it/offers/", offer.get("id")),
     "source": "justjoinit",
}
```
Indentationy 4 spacje , plus 79 znaków w linii, jak definiujesz coś listę to otwierasz nawias w jednej linii i zwykle przechodzisz do kolejnej i dopiero wtedy definiujesz wpis po wpisie i zamykasz w kolejnej linii (tak jak wyżej)

2019-12-06 13:21 UTC, Backscratcher approved these changes
Ślcznie, proszę merge'ować 👍

2019-12-06 13:29 UTC, merged