Exercise_2: Openweather_api_client
KatarzynaKopowska/Exercises pull request #3
Opened 2019-12-10 16:28 UTC by KatarzynaKopowska

2019-12-16 20:18 UTC, Backscratcher requested changes
Zobacz sobie komentarze ALE narazie do nich się nie odnoś. Znajdz w tej dokumentacji jeszcze jeden jakiś endpoint i przy pomocy swojej implementacji spróbuj dodać kolejny endpoint jaki obsługujesz w kodzie :)

2019-12-16 20:18 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +    city = None
To nie jest do końca dobrze użyte. A co jeśli poprosiłbym, że chcielibyśmy by API wspierało szukanie po lokalizacji ?

2019-12-16 20:18 UTC, Backscratcher commented on exercise_2/main.py
> +        current_weather = weather.parse_weather(complete_weather)
Hm, myślę, że parse_weather tak naprawdę może zawierać się w metodzie wyżej, tzn. get_weather. Chcemy, żeby ten API client był "czarną skrzynką". Używamy `get_weather` i oczekujemy uzyskania pogody, dodatkowy krok tzn. `parse_weather` trochę zaciemnia przydatność API danej bilbioteczki.

2019-12-16 20:18 UTC, Backscratcher commented on exercise_2/main.py
> +        sys.exit()
Nie musisz się martwić narazie takimi zamykaniami programów. Będziemy to robić imaczej i przy użyciu fajnych narzędzi :)

2019-12-16 20:18 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +    """Basic abstraction for services to handle serializing data from service
Oki, docstring jest fajny i sensowny i to jest coś czego bym oczekiwał, jednak nie ma to się jak do aktualnej implementacji.

2019-12-16 20:18 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +    city = "wisla"
Oj, zahardkowane miasto. Oj niedobrze.

2019-12-16 20:18 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +    url = "http://api.openweathermap.org/data/2.5/weather?q={}&APPID=bfc7d01991d939f6c91a824036ffcd34".format(city)
Oj, tutaj też kiepsko. Idea całkiem spoko ale trzeba to przerobić. Klasowa zmienna to nie jest droga tutaj.

2020-01-09 20:24 UTC, Backscratcher requested changes

2020-01-09 20:24 UTC, Backscratcher commented on exercise_2/main.py
> +        api_key="8141563408c821030aa7cdacd8bd0eff"
Po pierwsze, żadnych kluczy w repozytorium. Nigdy :D Absolutnie zakazane :D. Możesz zrobić tak, że dodasz plik, który się nazywa config.py albo pobierać to ze zmiennej środowiskowej i w kodzie powinno to wyglądać jakoś tak:
`api_key=config.OPENWEATHER_API_KEY`

2020-01-09 20:24 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +    """
Pustych docstringów nie zostawiamy

2020-01-09 20:24 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +class WeatherForecastManager:
Jest z tym wszystkim jeden problem. Mianowicie zrobiłaś manager'a, który przy odpaleniu run, zwraca dwie pogody. Nie chodziło tak naprawdę o to. Dobrze nadziałaś się na nadużywanie dziedziczenia, gdzie powinnaś użyć kompozycji. :D APIClient'y mają trochę inne zasady działania i design. Mianowicie:
`1. Inicjalizujesz clienta, podając jakiś klucz albo inne dane, które służą do autentykacji żeby nie przekazywac tego cały czas.`
`2. Wykonujesz jakąś metodę na API, która cuś robi i zwraca dane przy czym te dane sprowadza w jakimś cywilizowanym formacie.`
`3. Zwrotkę wykorzystujesz w swoim kodzie do np. powiadomienia klienta, że udało się wrzucić dane czy coś innego`

APIClient'y są tak gotową biblioteką/modułem, który obsługuje podstawowe operacje na jakimś Web'owym (zwykle REST'owym API). REST'owe API wyróżniają się w swoim design'ie tym, że końcówki (endpoint'y) odpowiadają za konkretne resource'y - tzn.:
`api/toys` - wiemy, że taka końcówka ma coś wspólnego z zabawkami, wykonanie na niej GET prawdpodobnie zwróci  dane o zabawkach.
`api/toys/sale` - taka końcówka zwróciłaby pewnie dane o zabawkach z przeceny.
Używając tego przykładu jako zrozumienia design'u i struktury byłoby.
`client = NonameAPIClient()`
`client.toys.get() zwróciloby info z api/toys/`
`client.toys.get_toys_from_sale() zwrociloby z api/toys/sale` Rozumisz ?

 Preferowanym design'em (wspomogę Cię) z strukturą logiczną odpowiadającą też temu REST'owemu design'owi byłoby coś takiego:
`openweather_client = OpenWeatherAPIClient(api_key=config.OPENWEATHER_API_KEY)`
`current = openweather_client.current_weather.get(q=London)   # przekazywane do zapytania jako kwargs np`
`forecast = openweather_client.five_days_forecast.get(q=London)`
W taki sposób oddzielasz implementacje końcówek od siebie (przez kompozycję `current_weather` `five_days_forecast`). Końcówki mogą mieć jakąś cześć wspólną (klasa bazowa, jakiś interfejs)
W obrębie jednej końcówki tzn. current_weather może być wiele metod tzn. current_weather.get current_weather.cos_innego ale musi to oczywiście odpowiadać temu na co pozwala openweather api. Nie mówię, że ten dizajn jest najlepszy ale jest całkiem logiczny i odpowiadający temu jak pisane są REST API. Co myślisz ? :D

2020-01-30 03:01 UTC, Backscratcher requested changes
Przepraszam, że z takim poślizgiem : (

2020-01-30 03:01 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +        self.api_key = api_key
W innym przypadku - np. kiedy byłby jakiś client który wykonuje requesty (tylko requesty) w bardziej skomplikowanych przypadkach api client wrapperów - wtedy powinnaś mieć instancję
`self.client = JakisClient() i przekazywać ją w parametrach do endpointów dla pełnego OOP experience :D

Chciałbym żebyś dodała jeszcze pole `base_url` które będzie od razu określało jakiej wersji api używamy:
`http://api.openweathermap.org/data/2.5/` i przekazywać ją do endpointów. To jest konfiguracja api clienta i ten obiekt powinien tym sterować.

2020-01-30 03:01 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +        self.current_weather = CurrentWeather(api_key)
w przypadku ^ lepiej przerzucić tworzenie tych endpointów do properties:
```
@property
def current_weather(self):
    return CurrentWeather(base_url, api_key)
```

2020-01-30 03:01 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +class CurrentWeather:
Polecam wydzielić klasę bazową, która się tu narzuca dla tych dwóch klas. Spróbuj :)

2020-01-30 03:01 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +        url = "http://api.openweathermap.org/data/2.5/weather?{}={}&APPID={}".format(
Musimy przykłady porobić z użyciem kwargsów z tego co widzę :D 
Między innymi jest problem z obecnym rozwiązaniem, mianowicie wspiera jedynie przekazanei tylko jednego klucza wartości do API a generalnie chcemy pozwalać na dowolność używania tego :)
W każdym razie, nie używaj tego tak. query params jest obsługiwane przez requests i nie musisz tego obrabiać w pythonie.
`weather_information = requests.get(url, params=kwargs)`

2020-01-30 03:01 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +            "current_weather": weather_information["weather"][0].get("main"),
Polecałbym unifikacje [klucz] pozmieniać na get(klucz) bo jest to bezpieczniejsze i lepiej skupić się na jednej metodzie :)
Druga sprawa nie wiem czemu wyciągasz stamtąd tylko [0] pierwszą wartość z listy. Dlatego w takich przypadakch (nieoczywistych) dodawaj komentarze i docstringi też :)

2020-01-30 10:08 UTC, KatarzynaKopowska commented on exercise_2/openweather_api_client.py
> +        self.api_key = api_key
Czy base_url ma być w config.py? Czy po prostu w inicie? 
Bo zarówno klasa CurrentWeather, jak i FiveDayForecast mają inny base_url

2020-01-31 12:31 UTC, Backscratcher requested changes

2020-01-31 12:31 UTC, Backscratcher commented on exercise_2/openweather_api_client.py
> +    # Get index [0] from json to get dict values from nested list
Ostatnia rzecz - nie tak robisz docstringi albo inline komentarze:

```
zmienna = tutajrobimy.jakies_mroczne_machinacje[0].get("lojezu", [])  # dwie spacje, gwiazda i komentarz
```

albo docstring:
```
def get(self, **kwargs):
    """To jest docstring do metody sialalalalal"""
```

Wincyj tutej https://www.python.org/dev/peps/pep-0257/

2020-01-31 13:38 UTC, Backscratcher approved these changes
Jest gicik Kasia :)

2020-01-31 14:09 UTC, merged